### ISSUE TITLE
When will the code be uploaded?

### ISSUE THREAD

**Issue by Vijayraven95** [Herrccc/DR-TANet#1]
Dear Author, The Architecture of the DR-TANet is interesting. I would like to use it for our work. hope the code will be uploaded here soon. Thanks for the good work.

**Comment by Herrccc** [comment]
Hi,

Thank you for your interest in my work.

It's estimated that our code will be available this weekend.

I hope it would be useful for your research.

Best regards,
Shuo Chen

Am Fr., 11. Juni 2021 um 11:27 Uhr schrieb Vijaya Raghavan <
***@***.***>:
